### ISSUE TITLE
Post catch update meeting todo

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#67]
- [x] add section in WP about stock definition in 2009 and that we are explicitly not including stat area 12 here
- [x] Add a note clarifying about how bait is included in discards but should actually have 100% mortality - attempt to quantify for text
- [x] Add a line in the plot to show divide pre- and post- 2006 for longline discards - why suddenly appear - about 300,000?
- [x] Include any 2006 discard counts
- [x] Exclude area 12 but be very clear about that
- [ ] Provide a table to help convert between dead dogfish and scientific catch for SAR
- [ ] help GMU convert to IFMP catch outside of SAR
- [x] likely switch to dead catch as round unit in projections
- [x] update catch in all data.ss, re-run all models
